# Generated by Django 4.1.7 on 2023-04-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_shop_strip_account_id_alter_cart_item_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='strip_account_id',
            new_name='stripe_account_id',
        ),
    ]
