# Generated by Django 4.1.7 on 2023-04-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_strip_account_id_shop_stripe_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='stripe_trx_id',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
