# Generated by Django 4.1.7 on 2023-04-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_transaction_stripe_trx_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='stripe_trx_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
