# Generated by Django 4.1.7 on 2023-04-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_transaction_stripe_trx_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='banner_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='profile_img',
            field=models.ImageField(default='https://imgur.com/a/kjXwMXC', upload_to='images/'),
            preserve_default=False,
        ),
    ]
