# Generated by Django 4.1.7 on 2023-04-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_shop_banner_img_shop_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
