# Generated by Django 4.1.7 on 2023-04-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='banner_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
