# Generated by Django 4.1.7 on 2023-04-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='email',
            field=models.EmailField(default='non@none.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='phone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='social_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
