# Generated by Django 4.1.7 on 2023-03-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
