# Generated by Django 4.1.7 on 2023-03-28 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
    ]
