# Generated by Django 4.1.7 on 2023-04-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_remove_member_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
